<!-- 
RSS generated by JIRA (6.3.4#6332-sha1:51bc225ef474afe3128b2f66878477f322397b16) at Sun May 17 03:15:50 UTC 2015

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
For example:
https://issues.apache.org/jira/si/jira.issueviews:issue-xml/DERBY-5601/DERBY-5601.xml?field=key&amp;field=summary
-->
<rss version="0.92" >
<channel>
    <title>ASF JIRA</title>
    <link>https://issues.apache.org/jira</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-uk</language>    <build-info>
        <version>6.3.4</version>
        <build-number>6332</build-number>
        <build-date>15-08-2014</build-date>
    </build-info>

<item>
            <title>[DERBY-5601] Windows hang in NativeAuthenticationServiceTest testAll with prior interrupt error in SecureServerTest and other cascade errors and failures</title>
                <link>https://issues.apache.org/jira/browse/DERBY-5601</link>
                <project id="10594" key="DERBY">Derby</project>
                    <description>&lt;p&gt;The IBM Windows runs on trunk  have been hanging  in NativeAuthenticationServiceTest.  This is preventing tests from continuing or being posted. The actual test run hangs at :&lt;br/&gt;
....&lt;br/&gt;
emb)lang.AutoIncrementTest.test_4437_03_deferredInsert used 218 ms .&lt;br/&gt;
(emb)lang.HalfCreatedDatabaseTest.test_4589 used 6859 ms .&lt;br/&gt;
(emb)lang.HalfCreatedDatabaseTest.test_5526 used 16 ms .&lt;br/&gt;
(emb)lang.NativeAuthenticationServiceTest.testAll used 24061 ms .&lt;br/&gt;
(emb)lang.NativeAuthenticationServiceTest.testAll used 17781 ms .&lt;br/&gt;
(emb)lang.NativeAuthenticationServiceTest.testAll used 11187 ms .&lt;br/&gt;
(net)lang.NativeAuthenticationServiceTest.testAll used 18187 ms .&lt;br/&gt;
(net)lang.NativeAuthenticationServiceTest.testAll &lt;/p&gt;

&lt;p&gt;and so no test continue and no results get posted to:&lt;br/&gt;
&lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/main/windows/testSummary-1239981.html&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/main/windows/testSummary-1239981.html&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;The last run where this did not happen was:&lt;br/&gt;
&lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/main/windows/testSummary-1236968.html&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/main/windows/testSummary-1236968.html&lt;/a&gt;&lt;/p&gt;


&lt;p&gt;The actual command being executed is:&lt;br/&gt;
       1  4748  2676  0 20:23:24 CONIN$ 46:30 C:\WINDOWS\system32\java.exe -Dder&lt;br/&gt;
byTesting.ldapServer=socket.usca.ibm.com -DderbyTesting.ldapPort=389 -DderbyTest&lt;br/&gt;
ing.dnString=oakland.ibm.com -DderbyTesting.ldapUser=mamta -DderbyTesting.ldapPa&lt;br/&gt;
ssword=xxxxx  -Xmx512M -Dderby.tests.networkServerStartTimeout=480 -Dderby.te&lt;br/&gt;
sts.basePort=3100 -Dderby.tests.trace=true -DderbyTesting.oldReleasePath=d:/jart&lt;br/&gt;
est/releases_for_upgrade_tests junit.textui.TestRunner org.apache.derbyTesting.f&lt;br/&gt;
unctionTests.suites.All&lt;/p&gt;

&lt;p&gt;I couldn&apos;t reproduce this running the single test on my machine.  Marking this blocker as the Oracle Nightlies seem to be having serious issues too that date back further.&lt;br/&gt;
&lt;a href=&quot;http://dbtg.foundry.sun.com/derby/test/Daily/jvm1.6/testing/Limited/&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://dbtg.foundry.sun.com/derby/test/Daily/jvm1.6/testing/Limited/&lt;/a&gt;&lt;/p&gt;


&lt;p&gt;Right now we have no reliable regression testing going on.&lt;/p&gt;

</description>
                <environment></environment>
        <key id="12541126">DERBY-5601</key>
            <summary>Windows hang in NativeAuthenticationServiceTest testAll with prior interrupt error in SecureServerTest and other cascade errors and failures</summary>
                <type id="1" iconUrl="https://issues.apache.org/jira/images/icons/issuetypes/bug.png">Bug</type>
                                            <priority id="1" iconUrl="https://issues.apache.org/jira/images/icons/priorities/blocker.png">Blocker</priority>
                        <status id="6" iconUrl="https://issues.apache.org/jira/images/icons/statuses/closed.png" description="The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.">Closed</status>
                    <statusCategory id="3" key="done" colorName="green"/>
                                    <resolution id="3">Duplicate</resolution>
                                        <assignee username="-1">Unassigned</assignee>
                                    <reporter username="kmarsden">Kathey Marsden</reporter>
                        <labels>
                    </labels>
                <created>Fri, 3 Feb 2012 20:19:01 +0000</created>
                <updated>Mon, 17 Jun 2013 10:19:43 +0100</updated>
                            <resolved>Thu, 16 Feb 2012 23:05:21 +0000</resolved>
                                    <version>10.9.1.0</version>
                                                    <component>Services</component>
                    <component>Test</component>
                        <due></due>
                            <votes>0</votes>
                                    <watches>1</watches>
                                                                <comments>
                            <comment id="13200098" author="kmarsden" created="Fri, 3 Feb 2012 22:14:47 +0000"  >&lt;p&gt;Temporarily disabled the test to see if we can get tests running again. Dag reports infrastructure problems in the Oracle runs. There have been simultaneous infrastructure changes in the IBM recently which confused me thinking that was the reason, but clearly it is this test that has consistently been hanging since the Monday Jan 30, 1238138 run.&lt;/p&gt;
</comment>
                            <comment id="13201484" author="kmarsden" created="Mon, 6 Feb 2012 19:17:58 +0000"  >&lt;p&gt;Posted this info on the list, but putting here to keep history in Jira.  Myrna is investigating why cygwin upgrade may have caused this issue.&lt;/p&gt;

&lt;p&gt;Talking with Myrna, Mike and Mamta and looking back at the onset of the NativeAuthenticationTest hang.  I see that even at that time we had the prior SecureServerTest failure&lt;/p&gt;

&lt;p&gt;(net)derbynet.SecureServerTest.testServerStartup used 6750 ms E.&lt;br/&gt;
(net)derbynet.SecureServerTest.testServerStartup used 46827 ms F.&lt;br/&gt;
Which we found later to have the stack Trace below &lt;span class=&quot;error&quot;&gt;&amp;#91;1&amp;#93;&lt;/span&gt; and which seemed to send things going down hill and led up to the hang, so may be related.&lt;br/&gt;
Myrna also told me at the  the time this all started, she just switched over to cygwin from another shell program.&lt;/p&gt;

&lt;p&gt;I have done suites.All runs sane and insane on my Windows machine as have Mike and Mamta and runs are clean, so I think it would be good to reenable NativeAuthenticationServiceTest on non-windows platforms and even on windows for non-ibm jvm&apos;s.&lt;br/&gt;
Myrna is working on figuring out why the cygwin upgrade caused such trouble on this machine.  I will do this tomorrow unless someone else beats me to it.&lt;/p&gt;


&lt;p&gt;Thanks&lt;/p&gt;

&lt;p&gt;Kathey&lt;/p&gt;

&lt;p&gt;&lt;span class=&quot;error&quot;&gt;&amp;#91;1&amp;#93;&lt;/span&gt; SecureServerTest( Opened = false, Authenticated= false, CustomDerbyProperties= null, WildCardHost= null )java.lang.InterruptedException&lt;br/&gt;
	at org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:184)&lt;br/&gt;
	at org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:146)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runServerCommand(SecureServerTest.java:481)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runsysinfo(SecureServerTest.java:411)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.testServerStartup(SecureServerTest.java:350)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:116)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;/p&gt;

</comment>
                            <comment id="13202506" author="kmarsden" created="Tue, 7 Feb 2012 16:23:04 +0000"  >&lt;p&gt;Much conversation on this issue is occurring on the derby-dev list on the thread &lt;span class=&quot;error&quot;&gt;&amp;#91;URGENT&amp;#93;&lt;/span&gt; Critical test situation on trunk&lt;br/&gt;
&lt;a href=&quot;http://old.nabble.com/-URGENT--Critical-test-situation-on-trunk-td33259629.html&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://old.nabble.com/-URGENT--Critical-test-situation-on-trunk-td33259629.html&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Also changed summary to include prior errors/failures leading up to the hang&lt;/p&gt;</comment>
                            <comment id="13203384" author="myrna" created="Wed, 8 Feb 2012 08:50:37 +0000"  >&lt;p&gt;I used various old saved builds of derby and found the problem starts happening with builds including revision 1159337 (&lt;a href=&quot;http://svn.apache.org/viewvc?view=revision&amp;amp;revision=1159337&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://svn.apache.org/viewvc?view=revision&amp;amp;revision=1159337&lt;/a&gt;), and not before. &lt;/p&gt;

&lt;p&gt;I also ran with Kristian&apos;s patch, which gives some output to the console:&lt;br/&gt;
(net)derbynet.SecureServerTest.testServerStartup START-SPAWNED:&lt;span class=&quot;error&quot;&gt;&amp;#91;-Demma.verbosity.level=silent, org.apache.derby.drda.NetworkServerControl, -p, 1527, sysinfo&amp;#93;&lt;/span&gt; STANDARD OUTPUT: exit code=-1&lt;br/&gt;
--------- Derby Network Server Information --------&lt;br/&gt;
Version: CSS10090/10.9.0.0 alpha - (1241655M)  Build: 1241655M  DRDA Product Id: CSS10090&lt;br/&gt;
derby.drda.maxThreads=0&lt;br/&gt;
derby.drda.sslMode=off&lt;br/&gt;
derby.drda.keepAlive=true&lt;br/&gt;
derby.drda.minThreads=0&lt;br/&gt;
derby.drda.portNumber=1527&lt;br/&gt;
derby.drda.logConnections=false&lt;br/&gt;
derby.drda.timeSlice=0&lt;br/&gt;
derby.drda.startNetworkServer=false&lt;br/&gt;
derby.drda.host=localhost&lt;br/&gt;
derby.drda.traceAll=false&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;sysinfo output for revision 10.9.0.0 alpha - (1241655M)&amp;#93;&lt;/span&gt; &lt;br/&gt;
END-SPAWNED  :&lt;span class=&quot;error&quot;&gt;&amp;#91;-Demma.verbosity.level=silent, org.apache.derby.drda.NetworkServerControl, -p, 1527, sysinfo&amp;#93;&lt;/span&gt; STANDARD OUTPUT:&lt;br/&gt;
used 5437 ms E.&lt;br/&gt;
(net)derbynet.SecureServerTest.testServerStartup used 13875 ms F.&lt;/p&gt;

&lt;p&gt;(Soon) after this, I killed the java process&lt;/p&gt;

&lt;p&gt;In the fail directory, this is the error stack:&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;Error/failure logged at Tue Feb 07 16:02:19 PST 2012&amp;#93;&lt;/span&gt;&lt;br/&gt;
java.lang.InterruptedException: process exited with code 0&lt;br/&gt;
	at org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:234)&lt;br/&gt;
	at org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:150)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runServerCommand(SecureServerTest.java:481)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runsysinfo(SecureServerTest.java:411)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.testServerStartup(SecureServerTest.java:350)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at java.lang.reflect.Method.invoke(Method.java:600)&lt;br/&gt;
	at junit.framework.TestCase.runTest(TestCase.java:164)&lt;br/&gt;
	at junit.framework.TestCase.runBare(TestCase.java:130)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:116)&lt;br/&gt;
	at junit.framework.TestResult$1.protect(TestResult.java:106)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.framework.TestResult.run(TestResult.java:109)&lt;br/&gt;
	at junit.framework.TestCase.run(TestCase.java:120)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.textui.TestRunner.doRun(TestRunner.java:121)&lt;br/&gt;
	at junit.textui.TestRunner.start(TestRunner.java:185)&lt;br/&gt;
	at junit.textui.TestRunner.main(TestRunner.java:143)&lt;/p&gt;

&lt;p&gt;&lt;span class=&quot;error&quot;&gt;&amp;#91;Error/failure logged at Tue Feb 07 16:02:37 PST 2012&amp;#93;&lt;/span&gt;&lt;br/&gt;
junit.framework.AssertionFailedError: directory trace does not exist&lt;br/&gt;
	at junit.framework.Assert.fail(Assert.java:47)&lt;br/&gt;
	at junit.framework.Assert.assertTrue(Assert.java:20)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.setTraceDirectory(SecureServerTest.java:382)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.testServerStartup(SecureServerTest.java:352)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at java.lang.reflect.Method.invoke(Method.java:600)&lt;br/&gt;
	at junit.framework.TestCase.runTest(TestCase.java:164)&lt;br/&gt;
	at junit.framework.TestCase.runBare(TestCase.java:130)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:116)&lt;br/&gt;
	at junit.framework.TestResult$1.protect(TestResult.java:106)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.framework.TestResult.run(TestResult.java:109)&lt;br/&gt;
	at junit.framework.TestCase.run(TestCase.java:120)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.textui.TestRunner.doRun(TestRunner.java:121)&lt;br/&gt;
	at junit.textui.TestRunner.start(TestRunner.java:185)&lt;br/&gt;
	at junit.textui.TestRunner.main(TestRunner.java:143)&lt;/p&gt;

&lt;p&gt;derby.log is unexiting - just boots and shutdowns and stacks of &lt;br/&gt;
java.sql.SQLException: Database &apos;singleUse/oneuse0&apos; not found.&lt;br/&gt;
and &lt;br/&gt;
java.sql.SQLException: Database &apos;testbase&apos; not found.&lt;/p&gt;
</comment>
                            <comment id="13203474" author="kristwaa" created="Wed, 8 Feb 2012 11:06:58 +0000"  >&lt;p&gt;Thanks for running the test again, Myrna.&lt;/p&gt;

&lt;p&gt;I don&apos;t see anything in the output explaining the problem though.&lt;br/&gt;
The printing of stdout tells that the interrupt did happen (exit code = -1), but after the output has been read the process reports that it exited normally (exit code = 0).&lt;/p&gt;

&lt;p&gt;I think there may be a few issues with the code in SpawnedProcess; it doesn&apos;t seem to explicitly close the process streams, waitFor may hang forever, and more importantly, it doesn&apos;t reset the interrupt flag. The latter may be what&apos;s causing the cascade error/failures.&lt;br/&gt;
I&apos;ll write a patch for testing on the machine experiencing this issue.&lt;/p&gt;</comment>
                            <comment id="13204059" author="myrna" created="Wed, 8 Feb 2012 22:22:52 +0000"  >&lt;p&gt;I have been remiss - I did not pay proper attention to failures.&lt;br/&gt;
On the machine where I&apos;m seeing trouble, with 10.8.2.2 and 10.9 alpha versions before revision 1159337, the suites.All fails &lt;b&gt;before&lt;/b&gt; SecureServerTest: test_01_WrongUsage used 10969 ms E. &lt;br/&gt;
This is in test derbynet.NetworkServerControlApiTest. &lt;br/&gt;
The stack trace from the fail directory is similar to the interrupt error reported before: &lt;br/&gt;
--------------------------- &lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;Error/failure logged at Wed Feb 08 13:46:35 PST 2012&amp;#93;&lt;/span&gt;&lt;br/&gt;
java.lang.InterruptedException&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.readProcessOutput(BaseTestCase.java:763)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.assertExecJavaCmdAsExpected(BaseTestCase.java:507)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.derbynet.NetworkServerControlApiTest.test_01_WrongUsage(NetworkServerControlApiTest.java:91)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at java.lang.reflect.Method.invoke(Method.java:600)&lt;br/&gt;
	at junit.framework.TestCase.runTest(TestCase.java:164)&lt;br/&gt;
	at junit.framework.TestCase.runBare(TestCase.java:130)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:112)&lt;br/&gt;
	at junit.framework.TestResult$1.protect(TestResult.java:106)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.framework.TestResult.run(TestResult.java:109)&lt;br/&gt;
	at junit.framework.TestCase.run(TestCase.java:120)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.textui.TestRunner.doRun(TestRunner.java:121)&lt;br/&gt;
	at junit.textui.TestRunner.start(TestRunner.java:185)&lt;br/&gt;
	at junit.textui.TestRunner.main(TestRunner.java:143)&lt;br/&gt;
--------------------------- &lt;br/&gt;
So looks like this will happen at some point on a fast machine. Perhaps the check in of 1159337 improved matters, but didn&apos;t fix? &lt;br/&gt;
Myrna&lt;/p&gt;</comment>
                            <comment id="13204826" author="rhillegas" created="Thu, 9 Feb 2012 20:32:07 +0000"  >&lt;p&gt;I have set up an XP guest os under Virtual Box on my laptop. I have successfully run NativeAuthenticationServiceTest using the Windows versions of Java 5 and Java 6 from Oracle. The test did not hang for me. I ran the test against the state of the trunk after checking in the fix for &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-5607&quot; title=&quot;Deadlock in Java 5 VM when using NATIVE authentication with a client running in the same VM as the server&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-5607&quot;&gt;&lt;del&gt;DERBY-5607&lt;/del&gt;&lt;/a&gt;. It would be interesting to know if NativeAuthenticationServiceTest still hangs for you on your platform. Thanks.&lt;/p&gt;</comment>
                            <comment id="13205532" author="myrna" created="Fri, 10 Feb 2012 16:38:36 +0000"  >&lt;p&gt;Rick, I ran with a recent build (including Christian&apos;s interrupt flag reset for &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-5608&quot; title=&quot;BaseTestCase.readProcessOutput should read getInputStream()  and getErrorStream() in separate threads&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-5608&quot;&gt;&lt;del&gt;DERBY-5608&lt;/del&gt;&lt;/a&gt;) but with the NativeAuthenticationServiceTest re-enabled for windows and found no hang. It looks like the hang is gone, and the test can be re-enabled.&lt;/p&gt;

&lt;p&gt;I still see a multitude of failures though, so this issue cannot yet be closed.&lt;/p&gt;</comment>
                            <comment id="13205553" author="kristwaa" created="Fri, 10 Feb 2012 17:01:55 +0000"  >&lt;p&gt;&amp;gt; I still see a multitude of failures though, so this issue cannot yet be closed.&lt;/p&gt;

&lt;p&gt;Is it as bad as before, or is it somewhat better?&lt;br/&gt;
The hope was that those caused by shutdown errors would go away with the fix.&lt;/p&gt;</comment>
                            <comment id="13205561" author="myrna" created="Fri, 10 Feb 2012 17:25:41 +0000"  >&lt;p&gt;Unfortunately, and puzzlingly, it&apos;s exactly the same (except for more tests run because I re-activated NativeAuthenticationServiceTest for this run).&lt;br/&gt;
I&apos;m getting this behavior with just running:&lt;br/&gt;
   java -Dderby.tests.trace=true junit.textui.TestRunner org.apache.derbyTesting.functionTests.suites.All &amp;gt; outfile.out 2&amp;gt;&amp;amp;1&lt;/p&gt;

&lt;p&gt;Here&apos;s the interrupt exception with this latest run:&lt;br/&gt;
-------------------&lt;br/&gt;
1) test_01_WrongUsage(org.apache.derbyTesting.functionTests.tests.derbynet.NetworkServerControlApiTest)java.lang.InterruptedException&lt;br/&gt;
	at java.lang.ProcessImpl.waitFor(Native Method)&lt;br/&gt;
	at org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:215)&lt;br/&gt;
	at org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:176)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.readProcessOutput(BaseTestCase.java:774)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.assertExecJavaCmdAsExpected(BaseTestCase.java:508)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.derbynet.NetworkServerControlApiTest.test_01_WrongUsage(NetworkServerControlApiTest.java:81)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
----------------------------&lt;br/&gt;
and the second and third failures are just as before. &lt;/p&gt;

&lt;p&gt;Note that the interrupt error does occur now in a different test than when we first saw this.&lt;/p&gt;

&lt;p&gt;It&apos;s still not happening when I run the derbynet._Suite by itself, only when running suites.All.&lt;br/&gt;
I&apos;ll do the following experiments over the weekend:&lt;/p&gt;
&lt;ul class=&quot;alternate&quot; type=&quot;square&quot;&gt;
	&lt;li&gt;run without the redirect to file 2&amp;gt;&amp;amp;1 (perhaps there&apos;s a problem lobbing stdout and stderr together?)&lt;/li&gt;
	&lt;li&gt;run in a dos command shell&lt;/li&gt;
	&lt;li&gt;get a smaller suites.All subset&lt;/li&gt;
	&lt;li&gt;install a debugger and step through? (Probably won&apos;t get to this until Monday).&lt;/li&gt;
&lt;/ul&gt;


&lt;p&gt;Any other suggestions on what I could do to gather more information?&lt;/p&gt;</comment>
                            <comment id="13205590" author="mikem" created="Fri, 10 Feb 2012 18:12:02 +0000"  >&lt;p&gt;could you post the suites output of your current fail (just up and a little past the first failure is enough to get an idea of what tests are involved).  If it is as before then the first error happens very quickly (i think you said 2-3 minutes), and less than 50 fixtures.  &lt;/p&gt;

&lt;p&gt;I think best next step is just do binary search to narrow down tests run by suite.all, hopefully eliminating most tests before the failure and still&lt;br/&gt;
coming up with reproducible case in your environment.  At this point it seems like some test before the failing test is causing the issue, so narrowing down list of suspects would help.  &lt;/p&gt;</comment>
                            <comment id="13205601" author="kristwaa" created="Fri, 10 Feb 2012 18:21:36 +0000"  >&lt;p&gt;I agree with Mike.&lt;/p&gt;

&lt;p&gt;You could also move derbynet to the end of the run and see if it still happens then.&lt;br/&gt;
Another theory is that due to the interrupt the subprocess doesn&apos;t terminate and interferes with the tests. I&apos;ll have a patch for that soon...&lt;/p&gt;</comment>
                            <comment id="13205787" author="myrna" created="Fri, 10 Feb 2012 21:56:38 +0000"  >&lt;p&gt;I&apos;m attaching the console output from one of the failed runs (this one included Kristian&apos;s latest patch, and a modified lang._Suite so it ran NativeAuthenticationServiceTest).&lt;/p&gt;

&lt;p&gt;The test run on this machine with just DOS failed in the same test (NetworkServerControlAPITest.test_01_WrongUsage)&lt;/p&gt;</comment>
                            <comment id="13205790" author="myrna" created="Fri, 10 Feb 2012 21:58:01 +0000"  >&lt;p&gt;Forgot to mention; in the saved console output file I removed all failures and errors &amp;gt; 50, so there&apos;s stack traces of 50 errors and 50 failures.&lt;/p&gt;</comment>
                            <comment id="13205859" author="kmarsden" created="Fri, 10 Feb 2012 23:25:11 +0000"  >&lt;p&gt;I wonder if it would be helpful to print &lt;br/&gt;
System.out.println(&quot;isInterrupted() value: &quot; + Thread.currentThread().isInterrupted() );&lt;/p&gt;

&lt;p&gt;in BaseTestCase.runBare()&lt;/p&gt;

&lt;p&gt;I think that method is invoked for each test.&lt;/p&gt;</comment>
                            <comment id="13205942" author="dagw" created="Sat, 11 Feb 2012 01:00:39 +0000"  >&lt;p&gt;May not be relevant at all, but Derby does use interrupts itself in NetworkServerControlImpl in three places.&lt;/p&gt;</comment>
                            <comment id="13206721" author="kristwaa" created="Mon, 13 Feb 2012 07:09:19 +0000"  >&lt;p&gt;Attaching an extended version of SpawnedProcess, which isn&apos;t suspectible to interrupts when waiting for the process to complete.&lt;/p&gt;

&lt;p&gt;I&apos;ve let the uses of SpawnedProcess.complete behave as earlier, so if the interrupt seen earlier stopped us from waiting/destroying a process the test may now hang for 45 minutes before killing the process. For testing purposes you can set this to a lower value (use milliseconds) with derby.tests.process.killThreshold. This value must be higher than the time it takes to run the longest test using an external process, otherwise the process will be terminated prematurely. On a hang you should be able to use jstack to see where the code is waiting/stuck.&lt;/p&gt;

&lt;p&gt;I&apos;ve run suites.All with the patch on Windows Vista without errors, but there were no process-related issues in that run anyway.&lt;/p&gt;</comment>
                            <comment id="13207155" author="myrna" created="Mon, 13 Feb 2012 20:06:46 +0000"  >&lt;p&gt;I appreciate all the effort put into this issue...&lt;/p&gt;

&lt;p&gt;Unfortunately, I cannot build after installing the latest patch, I get:&lt;/p&gt;

&lt;p&gt;    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt; C:\derby\trunk\java\testing\org\apache\derbyTesting\junit\SpawnedProcess.java:23: cannot find symbol&lt;br/&gt;
    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt; import java.io.Closeable;&lt;br/&gt;
    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt;               ^&lt;br/&gt;
    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt;   symbol:   class Closeable&lt;br/&gt;
    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt;   location: package java.io&lt;br/&gt;
    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt; C:\derbyt\trunk\java\testing\org\apache\derbyTesting\junit\SpawnedProcess.java:381: cannot find symbol&lt;br/&gt;
    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt;     private void closeStream(Closeable stream) {&lt;br/&gt;
    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt;                              ^&lt;br/&gt;
    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt;   symbol:   class Closeable&lt;br/&gt;
    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt;   location: class SpawnedProcess&lt;br/&gt;
    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt; 2 errors&lt;br/&gt;
    &lt;span class=&quot;error&quot;&gt;&amp;#91;javac&amp;#93;&lt;/span&gt; Compile failed; see the compiler error output for details.&lt;/p&gt;</comment>
                            <comment id="13207223" author="mikem" created="Mon, 13 Feb 2012 21:26:01 +0000"  >&lt;p&gt;it built for me in a client using ibm16 in my path and ANT_JAVA set to jdk16, with nothing in my local.properties (most notably no jdk4lib* variable settings).  Closable looks like it was introduced in 1.5, so probably will not compile when using a pre&lt;br/&gt;
1.5 compiler or compiler directive.  I think there is some magic that needs to be put into directories that require higher than 1.5 to build.  If I add the&lt;br/&gt;
jdk14* lib settings to my local.properties I see the errors Myrna reports.&lt;/p&gt;

&lt;p&gt;I think this means that if we check the patch in that j2me based jvms no longer will be able to run tests that use SpawnedProcess.  And if we check it&lt;br/&gt;
in, probably needs a change to the build.xml file in the junit directory indicating that it need jdk15 libs for that file.  &lt;/p&gt;</comment>
                            <comment id="13207277" author="myrna" created="Mon, 13 Feb 2012 22:24:00 +0000"  >&lt;p&gt;I revised my properties and was able to get this to build...&lt;/p&gt;

&lt;p&gt;I&apos;ll try out the patch and post the results.&lt;/p&gt;

</comment>
                            <comment id="13207290" author="kristwaa" created="Mon, 13 Feb 2012 22:35:42 +0000"  >&lt;p&gt;Although I don&apos;t enjoy being stuck in the past, it wasn&apos;t my intension to break the J2ME support &lt;img class=&quot;emoticon&quot; src=&quot;https://issues.apache.org/jira/images/icons/emoticons/smile.gif&quot; height=&quot;16&quot; width=&quot;16&quot; align=&quot;absmiddle&quot; alt=&quot;&quot; border=&quot;0&quot;/&gt;&lt;br/&gt;
I first thought my IDE had fooled me, but it turns out that it was because PropertySetter has been simplified. After that happened I have not manually configured my build system to catch these issues.&lt;/p&gt;

&lt;p&gt;I&apos;ve attached a new verrsion of the patch.&lt;/p&gt;</comment>
                            <comment id="13207392" author="myrna" created="Tue, 14 Feb 2012 00:28:09 +0000"  >&lt;p&gt;The run with the first version of spawnedprocess_extended.diff - built with my local.properties modified from how I normally build - got past both tests that have shown problems before and is still happily chugging along.&lt;br/&gt;
So that&apos;s very promising - Thank You Kristian!&lt;br/&gt;
I&apos;ll interrupt that run now, pick up the latest patch, revert my build environment, and kick off a new run with the second version of that patch.&lt;/p&gt;</comment>
                            <comment id="13207433" author="myrna" created="Tue, 14 Feb 2012 01:25:29 +0000"  >&lt;p&gt;The second version of spawnedprocess_extended.diff built without trouble in my original build environment, and has also past the NetworkServerControlApiTest.test_01_WrongUsage, and the SecureServerTest without hitting any failures.&lt;br/&gt;
The test run is still going, but it&apos;s looking good so far.&lt;/p&gt;</comment>
                            <comment id="13207819" author="myrna" created="Tue, 14 Feb 2012 16:43:32 +0000"  >&lt;p&gt;The good news is, the last run did not show any problems with SpawnedProcess. &lt;br/&gt;
I think the latest patch to SpawnedProcess etc. is good to commit. &lt;/p&gt;

&lt;p&gt;Unfortunately, the run still keeled over in testBoundaries, as before, and had many failures after that, also as before, (apparently) because of Derby System Shutdown messages. &lt;br/&gt;
I&apos;ll see if I can analyze this failure further. &lt;/p&gt;

&lt;p&gt;1) testBoundaries(org.apache.derbyTesting.functionTests.tests.jdbcapi.InternationalConnectTest)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XJ001, SQLERRMC: java.security.AccessControlException�Access denied (java.io.FilePermission &lt;span class=&quot;error&quot;&gt;&amp;#91;editedpath&amp;#93;&lt;/span&gt;\system\AAAA&lt;span class=&quot;error&quot;&gt;&amp;#91;...editedfilenameforformatting...&amp;#93;&lt;/span&gt;AAA\tmp delete)�XJ001.U&lt;br/&gt;
	at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:99)&lt;br/&gt;
	at org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:364)&lt;br/&gt;
	at org.apache.derby.jdbc.ClientDriver.connect(ClientDriver.java:166)&lt;br/&gt;
	at java.sql.DriverManager.getConnection(DriverManager.java:317)&lt;br/&gt;
	at java.sql.DriverManager.getConnection(DriverManager.java:273)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbcapi.InternationalConnectTest.testBoundaries(InternationalConnectTest.java:120)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:51)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:18)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:51)&lt;br/&gt;
Caused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XJ001, SQLERRMC: java.security.AccessControlException�Access denied (java.io.FilePermission &lt;span class=&quot;error&quot;&gt;&amp;#91;editedpath&amp;#93;&lt;/span&gt;\system\AAA&lt;span class=&quot;error&quot;&gt;&amp;#91;...editedfilenameforformatting...&amp;#93;&lt;/span&gt;AAA\tmp delete)�XJ001.U&lt;br/&gt;
	at org.apache.derby.client.am.Connection.completeSqlca(Connection.java:2125)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseRdbAccessFailed(NetConnectionReply.java:538)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseAccessRdbError(NetConnectionReply.java:431)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseACCRDBreply(NetConnectionReply.java:294)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.readAccessDatabase(NetConnectionReply.java:121)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.readSecurityCheckAndAccessRdb(NetConnection.java:826)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.flowSecurityCheckAndAccessRdb(NetConnection.java:762)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.flowUSRIDONLconnect(NetConnection.java:603)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.flowConnect(NetConnection.java:410)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.&amp;lt;init&amp;gt;(NetConnection.java:220)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection40.&amp;lt;init&amp;gt;(NetConnection40.java:74)&lt;br/&gt;
	at org.apache.derby.client.net.ClientJDBCObjectFactoryImpl40.newNetConnection(ClientJDBCObjectFactoryImpl40.java:269)&lt;br/&gt;
	at org.apache.derby.jdbc.ClientDriver.connect(ClientDriver.java:100)&lt;br/&gt;
	... 41 more&lt;/p&gt;</comment>
                            <comment id="13207823" author="myrna" created="Tue, 14 Feb 2012 16:50:26 +0000"  >&lt;p&gt;The latest failures actually look like &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4836&quot; title=&quot;many failures with IBM 1.5 and 1.6 on windows after test InternationalConnectTest&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4836&quot;&gt;&lt;del&gt;DERBY-4836&lt;/del&gt;&lt;/a&gt;. I&apos;ll check on my jvm version.&lt;/p&gt;</comment>
                            <comment id="13207855" author="myrna" created="Tue, 14 Feb 2012 17:40:13 +0000"  >&lt;p&gt;Sure enough, I was picking up the wrong version because of the different PATH setting syntax for cygwin. Hence the cascading errors after InternationalConnectTest.&lt;/p&gt;

&lt;p&gt;Still, there was a hang in NativeAuthenticationServiceTest which Rick fixed, and I think the SpawnedProcess improvements are also valuable...So +1 to commit those changes.&lt;/p&gt;</comment>
                            <comment id="13208369" author="kristwaa" created="Wed, 15 Feb 2012 11:11:23 +0000"  >&lt;p&gt;Thanks for testing the SpawnedProcess patch, Myrna.&lt;br/&gt;
I&apos;ve created &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-5617&quot; title=&quot;Improve process handling in SpawnedProcess&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-5617&quot;&gt;&lt;del&gt;DERBY-5617&lt;/del&gt;&lt;/a&gt; to track that work.&lt;/p&gt;

&lt;p&gt;If you still have the logs (stdout and stderr), do you mind grepping for &apos;&lt;/p&gt;
{SpawnedProcess}
&lt;p&gt;&apos; and post whatever you find?&lt;br/&gt;
Also, did the test run take a lot longer than without the patch?&lt;/p&gt;</comment>
                            <comment id="13209748" author="myrna" created="Thu, 16 Feb 2012 21:20:36 +0000"  >&lt;p&gt;I removed the runs before I saw this message.&lt;br/&gt;
I did, however, check for SpawnedProcess and it did not show up anymore with the latest patch.&lt;/p&gt;

&lt;p&gt;I can run a suites.All run of the builds with and without your patch if you like to know the time difference, but that will take a while. I&apos;ll post that info in &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-5617&quot; title=&quot;Improve process handling in SpawnedProcess&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-5617&quot;&gt;&lt;del&gt;DERBY-5617&lt;/del&gt;&lt;/a&gt;.&lt;/p&gt;

&lt;p&gt;In the mean time, I think &lt;b&gt;this&lt;/b&gt; issue can be closed - perhaps &apos;invalid&apos; is the best, or perhaps &apos;duplicate&apos; as the cascading errors were a combination of my mistake and a jvm bug, the NativeAuthenticationTest and Interrupt errors are (being) addressed in different issues.&lt;/p&gt;</comment>
                            <comment id="13209864" author="myrna" created="Thu, 16 Feb 2012 23:05:21 +0000"  >&lt;p&gt;I am marking this as a duplicate of &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4836&quot; title=&quot;many failures with IBM 1.5 and 1.6 on windows after test InternationalConnectTest&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4836&quot;&gt;&lt;del&gt;DERBY-4836&lt;/del&gt;&lt;/a&gt;, because of the cascading errors after InternationalConnectTest.testBoundaries failure.&lt;br/&gt;
NativeAuthenticationTest issue has been fixed in &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-5608&quot; title=&quot;BaseTestCase.readProcessOutput should read getInputStream()  and getErrorStream() in separate threads&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-5608&quot;&gt;&lt;del&gt;DERBY-5608&lt;/del&gt;&lt;/a&gt;.&lt;br/&gt;
Using a later JVM version, I do not see an InterruptException, so that too is likely a jvm bug, or at least jvm-related.&lt;/p&gt;</comment>
                            <comment id="13210111" author="kristwaa" created="Fri, 17 Feb 2012 07:11:06 +0000"  >&lt;p&gt;It&apos;s not that important for me. If you have deleted the output, don&apos;t rerun the tests.&lt;/p&gt;</comment>
                            <comment id="13685336" author="knutanders" created="Mon, 17 Jun 2013 10:19:43 +0100"  >&lt;p&gt;&lt;span class=&quot;error&quot;&gt;&amp;#91;bulk update&amp;#93;&lt;/span&gt; Close all resolved issues that haven&apos;t been updated for more than one year.&lt;/p&gt;</comment>
                    </comments>
                <issuelinks>
                            <issuelinktype id="12310010">
                    <name>Incorporates</name>
                                            <outwardlinks description="incorporates">
                                        <issuelink>
            <issuekey id="12541864">DERBY-5607</issuekey>
        </issuelink>
                            </outwardlinks>
                                                        </issuelinktype>
                            <issuelinktype id="10030">
                    <name>Reference</name>
                                                                <inwardlinks description="is related to">
                                        <issuelink>
            <issuekey id="12476715">DERBY-4836</issuekey>
        </issuelink>
            <issuelink>
            <issuekey id="12541869">DERBY-5608</issuekey>
        </issuelink>
                            </inwardlinks>
                                    </issuelinktype>
                    </issuelinks>
                <attachments>
                            <attachment id="12514163" name="runsteall.out" size="416744" author="myrna" created="Fri, 10 Feb 2012 21:56:38 +0000"/>
                            <attachment id="12514408" name="spawnedprocess_extended.diff" size="21285" author="kristwaa" created="Mon, 13 Feb 2012 22:35:42 +0000"/>
                    </attachments>
                <subtasks>
                    </subtasks>
                <customfields>
                                                <customfield id="customfield_12310310" key="com.atlassian.jira.toolkit:attachments">
                        <customfieldname>Attachment count</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>2.0</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                        <customfield id="customfield_12310200" key="com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes">
                        <customfieldname>Bug behavior facts</customfieldname>
                        <customfieldvalues>
                                <customfieldvalue key="10369"><![CDATA[Regression Test Failure]]></customfieldvalue>
    
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                    <customfield id="customfield_12310220" key="com.atlassian.jira.ext.charting:firstresponsedate">
                        <customfieldname>Date of First Response</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>Wed, 8 Feb 2012 08:50:37 +0000</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                                                    <customfield id="customfield_12310420" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Global Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>226478</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                <customfield id="customfield_12311820" key="com.pyxis.greenhopper.jira:gh-lexo-rank">
                        <customfieldname>Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>2|hy0dnz:</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_12310920" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Rank (Obsolete)</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>36032</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                        <customfield id="customfield_12310222" key="com.atlassian.jira.ext.charting:timeinstatus">
                        <customfieldname>Time in Status</customfieldname>
                        <customfieldvalues>
                            
                        </customfieldvalues>
                    </customfield>
                                                                                            </customfields>
    </item>
</channel>
</rss>