<!-- 
RSS generated by JIRA (6.3.4#6332-sha1:51bc225ef474afe3128b2f66878477f322397b16) at Sun May 17 03:24:20 UTC 2015

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
For example:
https://issues.apache.org/jira/si/jira.issueviews:issue-xml/DERBY-6250/DERBY-6250.xml?field=key&amp;field=summary
-->
<rss version="0.92" >
<channel>
    <title>ASF JIRA</title>
    <link>https://issues.apache.org/jira</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-uk</language>    <build-info>
        <version>6.3.4</version>
        <build-number>6332</build-number>
        <build-date>15-08-2014</build-date>
    </build-info>

<item>
            <title>[DERBY-6250] nightly regression test failure: jdbc4.LoginTimeoutTest testBasic client/server java.sql.SQLTimeoutException: XBDA0, Login timeout Exceeded and junit.framework.AssertionFailedError: Should not have been able to connect!</title>
                <link>https://issues.apache.org/jira/browse/DERBY-6250</link>
                <project id="10594" key="DERBY">Derby</project>
                    <description>&lt;p&gt;intermittent nightly test failure:  10.10, windows, ibm16.  &lt;/p&gt;

&lt;p&gt;&lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/v10_10/windows/testlog/ibm16/1488453-suites.All_diff.txt&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/v10_10/windows/testlog/ibm16/1488453-suites.All_diff.txt&lt;/a&gt;&lt;br/&gt;
1) client/server LoginTimeoutTestjava.sql.SQLTimeoutException: DERBY SQL error: ERRORCODE: 40000, SQLSTATE: XBDA0, SQLERRMC: Login timeout exceeded.&lt;br/&gt;
	at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.jdbc.ClientDriver.connect(Unknown Source)&lt;br/&gt;
	at java.sql.DriverManager.getConnection(DriverManager.java:419)&lt;br/&gt;
	at java.sql.DriverManager.getConnection(DriverManager.java:391)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:100)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:67)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:47)&lt;br/&gt;
	at org.apache.derbyTesting.junit.TestConfiguration.openConnection(TestConfiguration.java:1737)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DropDatabaseSetup.tearDown(DropDatabaseSetup.java:54)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:22)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
Caused by: org.apache.derby.client.am.SqlException: DERBY SQL error: ERRORCODE: 40000, SQLSTATE: XBDA0, SQLERRMC: Login timeout exceeded.&lt;br/&gt;
	at org.apache.derby.client.am.Connection.completeSqlca(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseRdbAccessFailed(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseAccessRdbError(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseACCRDBreply(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.readAccessDatabase(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.readSecurityCheckAndAccessRdb(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.flowSecurityCheckAndAccessRdb(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.flowUSRIDPWDconnect(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.flowConnect(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.&amp;lt;init&amp;gt;(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection40.&amp;lt;init&amp;gt;(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.ClientJDBCObjectFactoryImpl40.newNetConnection(Unknown Source)&lt;br/&gt;
	... 36 more&lt;br/&gt;
There was 1 failure:&lt;br/&gt;
1) testBasic(org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest)junit.framework.AssertionFailedError: Should not have been able to connect!&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.tryTimeout(LoginTimeoutTest.java:312)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.tryTimeout(LoginTimeoutTest.java:302)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetConnector(LoginTimeoutTest.java:288)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetServerTimeout(LoginTimeoutTest.java:378)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetServerTimeouts(LoginTimeoutTest.java:365)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.testBasic(LoginTimeoutTest.java:282)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:117)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseJDBCTestCase.runBareOverridable(BaseJDBCTestCase.java:442)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseJDBCTestCase.runBare(BaseJDBCTestCase.java:459)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;/p&gt;</description>
                <environment></environment>
        <key id="12651186">DERBY-6250</key>
            <summary>nightly regression test failure: jdbc4.LoginTimeoutTest testBasic client/server java.sql.SQLTimeoutException: XBDA0, Login timeout Exceeded and junit.framework.AssertionFailedError: Should not have been able to connect!</summary>
                <type id="1" iconUrl="https://issues.apache.org/jira/images/icons/issuetypes/bug.png">Bug</type>
                                            <priority id="3" iconUrl="https://issues.apache.org/jira/images/icons/priorities/major.png">Major</priority>
                        <status id="1" iconUrl="https://issues.apache.org/jira/images/icons/statuses/open.png" description="The issue is open and ready for the assignee to start work on it.">Open</status>
                    <statusCategory id="2" key="new" colorName="blue-gray"/>
                                    <resolution id="-1">Unresolved</resolution>
                                        <assignee username="-1">Unassigned</assignee>
                                    <reporter username="mikem">Mike Matrigali</reporter>
                        <labels>
                    </labels>
                <created>Wed, 5 Jun 2013 19:54:20 +0100</created>
                <updated>Thu, 16 Oct 2014 19:13:35 +0100</updated>
                                            <version>10.10.2.0</version>
                                                    <component>Test</component>
                        <due></due>
                            <votes>0</votes>
                                    <watches>4</watches>
                                                                <comments>
                            <comment id="13746490" author="myrna" created="Wed, 21 Aug 2013 16:43:58 +0100"  >&lt;p&gt;Failed again here:&lt;br/&gt;
&lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm16/1516056-suites.All_diff.txt&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm16/1516056-suites.All_diff.txt&lt;/a&gt;&lt;/p&gt;</comment>
                            <comment id="13771018" author="mamtas" created="Wed, 18 Sep 2013 19:01:19 +0100"  >&lt;p&gt;Failed on 10.10(1524273) with IBM jdk 1.6&lt;br/&gt;
&lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/v10_10/windows/testlog/ibm16/1524273-suites.All_diff.txt&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/v10_10/windows/testlog/ibm16/1524273-suites.All_diff.txt&lt;/a&gt;&lt;/p&gt;</comment>
                            <comment id="13844653" author="myrna" created="Tue, 10 Dec 2013 20:48:04 +0000"  >&lt;p&gt;Failed on 10.10.1.3(1548790), ibm1.6 again: &lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/v10_10/windows/testlog/ibm16/1548790-suites.All_diff.txt&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/v10_10/windows/testlog/ibm16/1548790-suites.All_diff.txt&lt;/a&gt;&lt;/p&gt;</comment>
                            <comment id="13853541" author="myrna" created="Fri, 20 Dec 2013 00:58:12 +0000"  >&lt;p&gt;Failed again, trunk/windows (10.11.0.0 alpha (1552207)) with ibm 1.6 (SR15): &lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm16/1552207-suites.All_diff.txt&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm16/1552207-suites.All_diff.txt&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;I tried running the test 100 times (with sane jars), but that did not trip the issue.&lt;/p&gt;</comment>
                            <comment id="13853558" author="myrna" created="Fri, 20 Dec 2013 01:11:35 +0000"  >&lt;p&gt;This is the errorstacktrace.out in the fail directory:&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;Error/failure logged at Wed Dec 18 21:11:48 PST 2013&amp;#93;&lt;/span&gt;&lt;br/&gt;
junit.framework.AssertionFailedError: Should not have been able to connect!&lt;br/&gt;
	at junit.framework.Assert.fail(Assert.java:47)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.tryTimeout(LoginTimeoutTest.java:318)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.tryTimeout(LoginTimeoutTest.java:308)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetConnector(LoginTimeoutTest.java:295)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetServerTimeout(LoginTimeoutTest.java:384)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetServerTimeouts(LoginTimeoutTest.java:371)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.testBasic(LoginTimeoutTest.java:288)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at java.lang.reflect.Method.invoke(Method.java:611)&lt;br/&gt;
	at junit.framework.TestCase.runTest(TestCase.java:164)&lt;br/&gt;
	at junit.framework.TestCase.runBare(TestCase.java:130)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:118)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseJDBCTestCase.runBareOverridable(BaseJDBCTestCase.java:440)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseJDBCTestCase.runBare(BaseJDBCTestCase.java:457)&lt;br/&gt;
	at junit.framework.TestResult$1.protect(TestResult.java:106)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.framework.TestResult.run(TestResult.java:109)&lt;br/&gt;
	at junit.framework.TestCase.run(TestCase.java:120)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&lt;br/&gt;
	at junit.framework.TestSuite.run(TestSuite.java:225)&lt;br/&gt;
	at junit.textui.TestRunner.doRun(TestRunner.java:121)&lt;br/&gt;
	at junit.textui.TestRunner.start(TestRunner.java:185)&lt;br/&gt;
	at junit.textui.TestRunner.main(TestRunner.java:143)&lt;/p&gt;

&lt;p&gt;However, the timestamp in this is later than the content of derby.log, so I think the first test may be the problem.&lt;/p&gt;

&lt;p&gt;Here is the stack trace from derby.log in the fail directory:&lt;br/&gt;
Wed Dec 18 21:10:31 PST 2013:&lt;br/&gt;
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.0.0 alpha - (1552207): instance 67e28705-0143-0942-14ec-00000dcdcc80 &lt;br/&gt;
on database directory C:\jartest\JarResults.2013-12-18\ibm16_suites.All\system\singleUse\oneuse113 with class loader sun.misc.Launcher$AppClassLoader@9cf09cf &lt;br/&gt;
Loaded from &lt;a href=&quot;file:/C:/jartest/jars/derby.jar&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;file:/C:/jartest/jars/derby.jar&lt;/a&gt;&lt;br/&gt;
java.vendor=IBM Corporation&lt;br/&gt;
java.runtime.version=pwi3260sr15-20131017_01 (SR15)&lt;br/&gt;
java.fullversion=JRE 1.6.0 IBM J9 2.4 Windows Server 2008 R2 x86-32 jvmwi3260sr15-20131016_170922 (JIT enabled, AOT enabled)&lt;br/&gt;
J9VM - 20131016_170922&lt;br/&gt;
JIT  - r9_20130920_46510ifx2&lt;br/&gt;
GC   - GA24_Java6_SR15_20131016_1337_B170922&lt;br/&gt;
os.name=Windows Server 2008 R2&lt;br/&gt;
os.arch=x86&lt;br/&gt;
os.version=6.1 build 7601 Service Pack 1&lt;br/&gt;
derby.system.home=C:\jartest\JarResults.2013-12-18\ibm16_suites.All\system&lt;br/&gt;
Database Class Loader started - derby.database.classpath=&apos;&apos;&lt;br/&gt;
Wed Dec 18 21:10:58 PST 2013 Thread&lt;span class=&quot;error&quot;&gt;&amp;#91;Thread-696,5,main&amp;#93;&lt;/span&gt; (XID = 191), (SESSIONID = 26), (DATABASE = singleUse/oneuse113), (DRDAID = null), Cleanup action starting&lt;br/&gt;
java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..&lt;br/&gt;
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedConnection.&amp;lt;init&amp;gt;(Unknown Source)&lt;br/&gt;
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)&lt;br/&gt;
	at org.apache.derby.jdbc.InternalDriver$LoginCallable.call(Unknown Source)&lt;br/&gt;
	at org.apache.derby.jdbc.InternalDriver$LoginCallable.call(Unknown Source)&lt;br/&gt;
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)&lt;br/&gt;
	at java.util.concurrent.FutureTask.run(FutureTask.java:149)&lt;br/&gt;
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:906)&lt;br/&gt;
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:929)&lt;br/&gt;
	at java.lang.Thread.run(Thread.java:761)&lt;br/&gt;
Caused by: java.sql.SQLException: Connection authentication failure occurred.  Reason: Invalid authentication..&lt;br/&gt;
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)&lt;br/&gt;
	... 15 more&lt;br/&gt;
============= begin nested exception, level (1) ===========&lt;br/&gt;
java.sql.SQLException: Connection authentication failure occurred.  Reason: Invalid authentication..&lt;br/&gt;
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedConnection.&amp;lt;init&amp;gt;(Unknown Source)&lt;br/&gt;
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)&lt;br/&gt;
	at org.apache.derby.jdbc.InternalDriver$LoginCallable.call(Unknown Source)&lt;br/&gt;
	at org.apache.derby.jdbc.InternalDriver$LoginCallable.call(Unknown Source)&lt;br/&gt;
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)&lt;br/&gt;
	at java.util.concurrent.FutureTask.run(FutureTask.java:149)&lt;br/&gt;
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:906)&lt;br/&gt;
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:929)&lt;br/&gt;
	at java.lang.Thread.run(Thread.java:761)&lt;/p&gt;</comment>
                            <comment id="13887352" author="mamtas" created="Fri, 31 Jan 2014 01:33:32 +0000"  >&lt;p&gt;Test failed on 10.10.1.4 - (1561251) codeline with ibm jdk 1.6&lt;br/&gt;
&lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/v10_10/windows/testlog/ibm16/1561251-suites.All_diff.txt&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/v10_10/windows/testlog/ibm16/1561251-suites.All_diff.txt&lt;/a&gt;&lt;br/&gt;
1) client/server LoginTimeoutTest&lt;br/&gt;
java.sql.SQLTimeoutException: DERBY SQL error: ERRORCODE: 40000, SQLSTATE: XBDA0, SQLERRMC: Login timeout exceeded.&lt;br/&gt;
	at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.jdbc.ClientDriver.connect(Unknown Source)&lt;br/&gt;
	at java.sql.DriverManager.getConnection(DriverManager.java:419)&lt;br/&gt;
	at java.sql.DriverManager.getConnection(DriverManager.java:391)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:100)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:67)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:47)&lt;br/&gt;
	at org.apache.derbyTesting.junit.TestConfiguration.openConnection(TestConfiguration.java:1746)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DropDatabaseSetup.tearDown(DropDatabaseSetup.java:54)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:22)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
Caused by: org.apache.derby.client.am.SqlException: DERBY SQL error: ERRORCODE: 40000, SQLSTATE: XBDA0, SQLERRMC: Login timeout exceeded.&lt;br/&gt;
	at org.apache.derby.client.am.Connection.completeSqlca(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseRdbAccessFailed(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseAccessRdbError(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseACCRDBreply(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.readAccessDatabase(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.readSecurityCheckAndAccessRdb(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.flowSecurityCheckAndAccessRdb(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.flowUSRIDPWDconnect(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.flowConnect(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.&amp;lt;init&amp;gt;(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection40.&amp;lt;init&amp;gt;(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.net.ClientJDBCObjectFactoryImpl40.newNetConnection(Unknown Source)&lt;br/&gt;
	... 36 more&lt;br/&gt;
There was 1 failure:&lt;br/&gt;
1) testBasic(org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest)junit.framework.AssertionFailedError: Should not have been able to connect!&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.tryTimeout(LoginTimeoutTest.java:318)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.tryTimeout(LoginTimeoutTest.java:308)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetConnector(LoginTimeoutTest.java:294)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetServerTimeout(LoginTimeoutTest.java:384)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetServerTimeouts(LoginTimeoutTest.java:371)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.testBasic(LoginTimeoutTest.java:288)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:118)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseJDBCTestCase.runBareOverridable(BaseJDBCTestCase.java:442)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseJDBCTestCase.runBare(BaseJDBCTestCase.java:459)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;/p&gt;</comment>
                            <comment id="13893743" author="mamtas" created="Thu, 6 Feb 2014 20:16:42 +0000"  >&lt;p&gt;Another failure on 10.10.1.4 - (1564610) using IBM jdk 1.6 on Windows machine.&lt;br/&gt;
&lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/v10_10/windows/testlog/ibm16/1564610-suites.All_diff.txt&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/v10_10/windows/testlog/ibm16/1564610-suites.All_diff.txt&lt;/a&gt;&lt;/p&gt;</comment>
                            <comment id="13918597" author="myrna" created="Mon, 3 Mar 2014 21:32:24 +0000"  >&lt;p&gt;Looking at the failures reported, it seems that there are two ways this test fails:&lt;br/&gt;
1. with embedded only, and then the stack trace fails like this:&lt;br/&gt;
--------------------------&lt;br/&gt;
Should not have been able to connect!&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.tryTimeout(LoginTimeoutTest.java:318)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.tryTimeout(LoginTimeoutTest.java:308)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetConnector(LoginTimeoutTest.java:293)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.testBasic(LoginTimeoutTest.java:284)&lt;br/&gt;
....&lt;br/&gt;
-----------------------&lt;br/&gt;
2. apparently with network server &quot;only&quot; and then there are 1 failure and one error, with the interesting parts of the stack trace like this:&lt;br/&gt;
-----------------------&lt;br/&gt;
1) client/server LoginTimeoutTestjava.sql.SQLTimeoutException: DERBY SQL error: ERRORCODE: 40000, SQLSTATE: XBDA0, SQLERRMC: Login timeout exceeded.&lt;br/&gt;
	at org.apache.derby.client.am.SQLExceptionFactory.getSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.jdbc.ClientDriver.connect(Unknown Source)&lt;br/&gt;
	at java.sql.DriverManager.getConnection(DriverManager.java:419)&lt;br/&gt;
	at java.sql.DriverManager.getConnection(DriverManager.java:391)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:101)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:68)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:48)&lt;br/&gt;
	at org.apache.derbyTesting.junit.TestConfiguration.openConnection(TestConfiguration.java:1708)&lt;br/&gt;
	at org.apache.derbyTesting.junit.DropDatabaseSetup.tearDown(DropDatabaseSetup.java:52)&lt;br/&gt;
....&lt;br/&gt;
Caused by: org.apache.derby.client.am.SqlException: DERBY SQL error: ERRORCODE: 40000, SQLSTATE: XBDA0, SQLERRMC: Login timeout exceeded.&lt;br/&gt;
...&lt;br/&gt;
and the failure (below) then actually happens earlier:&lt;br/&gt;
...&lt;br/&gt;
1) testBasic(org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest)junit.framework.AssertionFailedError: Should not have been able to connect!&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.tryTimeout(LoginTimeoutTest.java:318)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.tryTimeout(LoginTimeoutTest.java:308)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetConnector(LoginTimeoutTest.java:295)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetServerTimeout(LoginTimeoutTest.java:384)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.vetServerTimeouts(LoginTimeoutTest.java:371)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbc4.LoginTimeoutTest.testBasic(LoginTimeoutTest.java:288)&lt;br/&gt;
...&lt;br/&gt;
-----------------------&lt;br/&gt;
So the login timeout exceeded message we get in teardown when the networkserver hits the &apos;could not connect&apos; problem.&lt;/p&gt;</comment>
                            <comment id="13919595" author="myrna" created="Tue, 4 Mar 2014 16:45:53 +0000"  >&lt;p&gt;I can make the test fail fairly easily if I shorten the sleep times.&lt;br/&gt;
However, I cannot reproduce the teardown error for the clientserver test (which I thought would be the easiest once there is a failure).&lt;/p&gt;</comment>
                            <comment id="13921699" author="myrna" created="Thu, 6 Mar 2014 00:20:21 +0000"  >&lt;p&gt;Attaching a patch which &lt;/p&gt;
&lt;ul class=&quot;alternate&quot; type=&quot;square&quot;&gt;
	&lt;li&gt;adds some more data to the error situation&lt;/li&gt;
	&lt;li&gt;increases the sleep time of the SluggishAuthenticator when we get around the test cases that have failed so far&lt;/li&gt;
	&lt;li&gt;adds hooks to modify the sleep time on the server to do so for the network server case.&lt;/li&gt;
&lt;/ul&gt;


&lt;p&gt;Review will be appreciated, otherwise I intend to check this in tomorrow.&lt;/p&gt;</comment>
                            <comment id="13923133" author="jira-bot" created="Thu, 6 Mar 2014 22:01:06 +0000"  >&lt;p&gt;Commit 1575065 from &lt;a href=&quot;https://issues.apache.org/jira/secure/ViewProfile.jspa?name=myrna&quot; class=&quot;user-hover&quot; rel=&quot;myrna&quot;&gt;Myrna van Lunteren&lt;/a&gt; in branch &apos;code/trunk&apos;&lt;br/&gt;
[ &lt;a href=&quot;https://svn.apache.org/r1575065&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://svn.apache.org/r1575065&lt;/a&gt; ]&lt;/p&gt;

&lt;p&gt;&lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-6250&quot; title=&quot;nightly regression test failure: jdbc4.LoginTimeoutTest testBasic client/server java.sql.SQLTimeoutException: XBDA0, Login timeout Exceeded and junit.framework.AssertionFailedError: Should not have been able to connect!&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-6250&quot;&gt;DERBY-6250&lt;/a&gt;; nightly regression test failure: jdbc4.LoginTimeoutTest testBasic client/server java.sql.SQLTimeoutException: XBDA0, Login timeout Exceeded and junit.framework.AssertionFailedError: Should not have been able to connect!&lt;br/&gt;
  attempt to add more time for failing situations, and add more details to error message on failure.&lt;/p&gt;</comment>
                            <comment id="13932345" author="jira-bot" created="Wed, 12 Mar 2014 20:51:09 +0000"  >&lt;p&gt;Commit 1576900 from &lt;a href=&quot;https://issues.apache.org/jira/secure/ViewProfile.jspa?name=myrna&quot; class=&quot;user-hover&quot; rel=&quot;myrna&quot;&gt;Myrna van Lunteren&lt;/a&gt; in branch &apos;code/branches/10.10&apos;&lt;br/&gt;
[ &lt;a href=&quot;https://svn.apache.org/r1576900&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://svn.apache.org/r1576900&lt;/a&gt; ]&lt;/p&gt;

&lt;p&gt;&lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-6250&quot; title=&quot;nightly regression test failure: jdbc4.LoginTimeoutTest testBasic client/server java.sql.SQLTimeoutException: XBDA0, Login timeout Exceeded and junit.framework.AssertionFailedError: Should not have been able to connect!&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-6250&quot;&gt;DERBY-6250&lt;/a&gt;; nightly regression test failure: jdbc4.LoginTimeoutTest testBasic client/server java.sql.SQLTimeoutException: XBDA0, Login timeout Exceeded and junit.framework.AssertionFailedError: Should not have been able to connect!&lt;br/&gt;
   backport of revision 1575065 from trunk; add more details to the error message on failure.&lt;/p&gt;</comment>
                            <comment id="13963120" author="myrna" created="Tue, 8 Apr 2014 17:06:51 +0100"  >&lt;p&gt;Saw this again; trunk svn updated to 1585638, windows 2008,  ibm 1.7 :&lt;br/&gt;
&lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm17/1585638-suites.All_diff.txt&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm17/1585638-suites.All_diff.txt&lt;/a&gt;&lt;/p&gt;</comment>
                            <comment id="14025425" author="myrna" created="Mon, 9 Jun 2014 18:43:09 +0100"  >&lt;p&gt;I have no useful ideas at this moment on how to fix this. Unassigning myself.&lt;/p&gt;</comment>
                            <comment id="14174045" author="myrna" created="Thu, 16 Oct 2014 19:13:35 +0100"  >&lt;p&gt;The patch was committed. The test still fails interemittently.&lt;/p&gt;</comment>
                    </comments>
                <issuelinks>
                            <issuelinktype id="10030">
                    <name>Reference</name>
                                                                <inwardlinks description="is related to">
                                        <issuelink>
            <issuekey id="12654832">DERBY-6275</issuekey>
        </issuelink>
                            </inwardlinks>
                                    </issuelinktype>
                    </issuelinks>
                <attachments>
                            <attachment id="12632975" name="DERBY-6250.diff" size="4601" author="myrna" created="Thu, 6 Mar 2014 00:20:21 +0000"/>
                    </attachments>
                <subtasks>
                    </subtasks>
                <customfields>
                                                <customfield id="customfield_12310310" key="com.atlassian.jira.toolkit:attachments">
                        <customfieldname>Attachment count</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>1.0</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                        <customfield id="customfield_12310200" key="com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes">
                        <customfieldname>Bug behavior facts</customfieldname>
                        <customfieldvalues>
                                <customfieldvalue key="10369"><![CDATA[Regression Test Failure]]></customfieldvalue>
    
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                    <customfield id="customfield_12310220" key="com.atlassian.jira.ext.charting:firstresponsedate">
                        <customfieldname>Date of First Response</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>Wed, 21 Aug 2013 15:43:58 +0000</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                                                    <customfield id="customfield_12310420" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Global Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>331512</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                <customfield id="customfield_12311820" key="com.pyxis.greenhopper.jira:gh-lexo-rank">
                        <customfieldname>Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>2|hzf193:</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_12310920" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Rank (Obsolete)</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>331844</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                </customfields>
    </item>
</channel>
</rss>