Connection.close() method inconsistently throws exception on closed connection