The test jdbcapi.InvalidLDAPServerAuthenticationTest.testInvalidLDAPServerConnectionError fails in an assert:
    assertTrue(se.getMessage().indexOf("java.net.UnknownHostException")>1)

The error reported is:
Connection refused : javax.naming.CommunicationException: noSuchServer:389 [Root exception is java.net.ConnectException: Connection timed out]

The failure is reproducible.